### ISSUE TITLE
[Newbie question] typing_on example

### ISSUE THREAD

**Issue by asarialtun** [hyperoslo/facebook-messenger#123]
bot.rb example or readme document could include examples on usage of the following methods:
typing_on
typing_off
mark_seen
I have been recieving errors with ways I tried using them.

**Comment by jgorset** [comment]
Hi @asarialtun! We're already documenting this in the [README](https://github.com/hyperoslo/facebook-messenger#typing-indicator).

**Comment by jgorset** [comment]
I [improved the README to document it in context](https://github.com/hyperoslo/facebook-messenger/commit/e66bb473a158eb9e0116e0d1b006a77cda5292f7).

**Comment by server-izetov** [comment]
Hi @jgorset 
For some reason, I've catch:
`undefined method `typing_on' for #<Facebook::Messenger::Incoming::Message:0x00000003be64c0>`
```
/home/server/projects/example_bot/app/bot/bot.rb:7:in `block in <top (required)>'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/bot.rb:64:in `trigger'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/bot.rb:56:in `receive'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/server.rb:135:in `block (2 levels) in trigger'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/server.rb:134:in `each'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/server.rb:134:in `block in trigger'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/server.rb:128:in `each'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/server.rb:128:in `trigger'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/server.rb:50:in `receive'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/server.rb:29:in `call'
/home/server/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.11.1/lib/facebook/messenger/server.rb:19:in `call'
.......
```
my code is:
```
require 'facebook/messenger'

include Facebook::Messenger

Bot.on :message do |message|
  begin
    message.typing_on
  rescue Exception => e
    puts e.message
    puts e.backtrace.join("\n")
  end
end
```

**Comment by vholovatyy** [comment]
Getting same issue on both `typing_on` & `mark_seen` methods

**Comment by harrysmartboy** [comment]
Hi bit
