### ISSUE TITLE
Facebook Messenger throwing " An active access token must be used to query information about the current user. " even though page access token is correct

### ISSUE THREAD

**Issue by samuelharden** [hyperoslo/facebook-messenger#78]
```
/home/kushal/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.10.0/lib/facebook/messenger/thread.rb:36:in `raise_errors': An active access token must be used to query information about the current user. (Facebook::Messenger::Thread::Error)
	from /home/kushal/.rvm/gems/ruby-2.3.1/gems/facebook-messenger-0.10.0/lib/facebook/messenger/thread.rb:21:in `set'
	from /home/kushal/AcquireTech/shopick/app/bot/shopick.rb:119:in `<top (required)>'
	from /home/kushal/.rvm/gems/ruby-2.3.1@global/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `load'
	from /home/kushal/.rvm/gems/ruby-2.3.1@global/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /home/kushal/.rvm/gems/ruby-2.3.1@global/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /home/kushal/.rvm/gems/ruby-2.3.1@global/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:456:in `load_file'
	from /home/kushal/.rvm/gems/ruby-2.3.1@global/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:354:in `require_or_load'
```

Hi while setting the thread configuration, i am getting above error and rails exits. I have tried to regenerate the token and update token but that isn't helping.
P.S Earlier it was working but suddenly stopped working

**Comment by enderahmetyurt** [comment]
How do you set API_KEY static or reading from an ENV variable? I guess if you set ENV variable set for API_KEY you should check that it's right there.

**Comment by samuelharden** [comment]
Found the issue it was failing in development only.

Reason for failure was while configuring i added Facebook::Messenger.configure after 

```
`unless Rails.env.production?
  bot_files = Dir[Rails.root.join('app', 'bot', '**', '*.rb')]
  bot_reloader = ActiveSupport::FileUpdateChecker.new(bot_files) do
    bot_files.each{ |file| require_dependency file }
  end

  ActionDispatch::Callbacks.to_prepare do
    bot_reloader.execute_if_updated
  end

  bot_files.each { |file| require_dependency file }
end
`
```
block.

hence key was not available n development when files dependency were loaded and executed

**Comment by samuelharden** [comment]
@enderahmetyurt  Thanks for the quick reply :+1:
