### ISSUE TITLE
An active access token must be used to query information about the current user ?

### ISSUE THREAD

**Issue by prdpspkt** [hyperoslo/facebook-messenger#87]
I'm getting error saying 'An active access token must be used to query information about the current user' my code is here.

`Facebook::Messenger.config do |config|`
      `config.ACCESS_TOKEN = 'EAAX9oMZBEIAMBAFBgGPw2C7SymERdXSa7qyQjx4hwbZA6Mn03qVMIeOENGsotu659MOZCtKSujSVvPoZANkV5Cy5IscFOCEqH7EAak8SY9sJ2FhldWNcZBvLiUpsMYmbTYoIkyYDwWLA1HPoXdLrTz1HmJFqhg7bno2NXEmA4bAZDZD'`
         `config.VERIFY_TOKEN = 'my_voice_is_my_password_verify_me'`
       `config.APP_SECRET = "8bf7d61b66b1a6ad16f7c630e8febb92"`
`end`
`Facebook::Messenger::Subscriptions.subscribe`

Please help

**Comment by jgorset** [comment]
Which version are you using, and what is the stack trace, @prdpspkt?

**Comment by prdpspkt** [comment]
Here is trace in console: 
``` /app/vendor/bundle/ruby/2.2.0/gems/facebook-messenger-0.10.0/lib/facebook/messenger/subscriptions.rb:32:in `raise_errors': An active access token must be used to query information about the current user. (Facebook::Messenger::Subscriptions::Error)
2016-11-11T23:04:09.549093+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/facebook-messenger-0.10.0/lib/facebook/messenger/subscriptions.rb:18:in `subscribe'
2016-11-11T23:04:09.549094+00:00 app[web.1]:    from /app/app/bot/listen.rb:7:in `<top (required)>'
2016-11-11T23:04:09.549096+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
2016-11-11T23:04:09.549097+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
2016-11-11T23:04:09.549099+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
2016-11-11T23:04:09.549120+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:380:in `block in require_or_load'
2016-11-11T23:04:09.549135+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
2016-11-11T23:04:09.549117+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
2016-11-11T23:04:09.549139+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
2016-11-11T23:04:09.549138+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
2016-11-11T23:04:09.549157+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
2016-11-11T23:04:09.549141+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
2016-11-11T23:04:09.549143+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `load_interlock'
2016-11-11T23:04:09.549192+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:336:in `depend_on'
2016-11-11T23:04:09.549195+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
2016-11-11T23:04:09.549195+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:252:in `require_dependency'
2016-11-11T23:04:09.549198+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `each'
2016-11-11T23:04:09.549199+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `block in eager_load!'
2016-11-11T23:04:09.549201+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `each'
2016-11-11T23:04:09.549202+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `eager_load!'
2016-11-11T23:04:09.549204+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:354:in `eager_load!'
2016-11-11T23:04:09.549219+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:59:in `each'
2016-11-11T23:04:09.549222+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
2016-11-11T23:04:09.549222+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
2016-11-11T23:04:09.549224+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
2016-11-11T23:04:09.549225+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
2016-11-11T23:04:09.549239+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
2016-11-11T23:04:09.549241+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
2016-11-11T23:04:09.549243+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
2016-11-11T23:04:09.549244+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
2016-11-11T23:04:09.549245+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
2016-11-11T23:04:09.549246+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
2016-11-11T23:04:09.549246+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
2016-11-11T23:04:09.549248+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
2016-11-11T23:04:09.549249+00:00 app[web.1]:    from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
2016-11-11T23:04:09.549250+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
2016-11-11T23:04:09.549252+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
2016-11-11T23:04:09.549253+00:00 app[web.1]:    from /app/config/environment.rb:5:in `<top (required)>'
2016-11-11T23:04:09.549255+00:00 app[web.1]:    from /app/config.ru:3:in `require_relative'
2016-11-11T23:04:09.549269+00:00 app[web.1]:    from /app/config.ru:3:in `block in <main>'
2016-11-11T23:04:09.549269+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
2016-11-11T23:04:09.549270+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
2016-11-11T23:04:09.549274+00:00 app[web.1]:    from /app/config.ru:in `<main>'
2016-11-11T23:04:09.549273+00:00 app[web.1]:    from /app/config.ru:in `new'
2016-11-11T23:04:09.549276+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
2016-11-11T23:04:09.549277+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
2016-11-11T23:04:09.549281+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
2016-11-11T23:04:09.549283+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
2016-11-11T23:04:09.549279+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
2016-11-11T23:04:09.549285+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:59:in `app'
2016-11-11T23:04:09.549299+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
2016-11-11T23:04:09.549301+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/server.rb:282:in `start'
2016-11-11T23:04:09.549303+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:79:in `start'
2016-11-11T23:04:09.549304+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
2016-11-11T23:04:09.549306+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
2016-11-11T23:04:09.549307+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
2016-11-11T23:04:09.549309+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
2016-11-11T23:04:09.549327+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
2016-11-11T23:04:09.549359+00:00 app[web.1]:    from bin/rails:4:in `require'
2016-11-11T23:04:09.549362+00:00 app[web.1]:    from bin/rails:4:in `<main>'```

**Comment by prdpspkt** [comment]
Ok I used demo app that solved this problem.

**Comment by noamhacker** [comment]
@prdpspkt 
What do you mean by a demo app that solved this problem?
Thanks

**Comment by noamhacker** [comment]
Re-exported the access token variable to fix this
