### ISSUE TITLE
Facebook::Messenger::Bot::RecipientNotFound ((#100) No matching user found)

### ISSUE THREAD

**Issue by prdpspkt** [hyperoslo/facebook-messenger#90]
```016-11-12T04:54:11.504112+00:00 app[web.1]: [3c29e03d-8b90-4f57-b716-95ba002aac1c]
2016-11-12T04:54:11.504134+00:00 app[web.1]: [3c29e03d-8b90-4f57-b716-95ba002aac1c] Facebook::Messenger::Bot::RecipientNotFound ((#100) No matching user found):
2016-11-12T04:54:11.504209+00:00 app[web.1]: [3c29e03d-8b90-4f57-b716-95ba002aac1c]
2016-11-12T04:54:11.504260+00:00 app[web.1]: [3c29e03d-8b90-4f57-b716-95ba002aac1c] app/bots/product_bot.rb:78:in `ask'
2016-11-12T04:54:11.504263+00:00 app[web.1]: [3c29e03d-8b90-4f57-b716-95ba002aac1c] app/bots/product_bot.rb:168:in `block in <top (required)>'
2016-11-12T04:54:11.504459+00:00 app[web.1]: [3c29e03d-8b90-4f57-b716-95ba002aac1c] Error occurred while parsing request parameters.
2016-11-12T04:54:11.504461+00:00 app[web.1]: Contents:
2016-11-12T04:54:11.504461+00:00 app[web.1]:
2016-11-12T04:54:11.504462+00:00 app[web.1]:
2016-11-12T04:54:11.504645+00:00 app[web.1]: Error during failsafe response: no implicit conversion of nil into String
2016-11-12T04:54:11.504646+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.rc1/lib/action_dispatch/http/parameters.rb:71:in `rescue in parse_formatted_parameters'```

**Comment by jgorset** [comment]
This is likely an error in your application code, @prdpspkt. I would advise that you read all of [Facebook's documentation on bots](https://developers.facebook.com/docs/messenger-platform/guides), and specifically the documentation on how you reference users.

**Comment by manojmj92** [comment]
@prdpspkt This is probably because you are passing a recipient's ID that does not exist.
